export const stateConstants = {
	STATES: {
        PENDING_DISPATCH: '10',
        SCHEDULED: '-2',
		WIP: '18',
		ACCEPTED: '17',
		ASSIGNED: '16',
	},
};

export const tables = {
	USER_TABLE: 'sys_user',
	TASK_TABLE: 'task',
};

export const customActions = {
	INITIALIZE_MAP: 'FSM_GMAP#INITIALIZE_MAP',
	FETCH_AGENT_DATA: 'FSM_GMAP#AGENT_DATA_FETCH_REQUESTED',
	FETCH_TASK_DATA: 'FSM_GMAP#TASK_DATA_FETCH_REQUESTED',
	FETCH_AGENT_DATA_SUCCESS: 'FSM_GMAP#AGENT_DATA_FETCH_SUCCEEDED',
	FETCH_TASK_DATA_SUCCESS: 'FSM_GMAP#TASK_DATA_FETCH_SUCCEEDED'
};
